# Generated by Django 6.0.6 on 2026-07-01 11:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Approvisionnement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('type_materiel', models.CharField(max_length=100)),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unite_mesure', models.CharField(max_length=50)),
                ('fournisseur', models.CharField(max_length=255)),
                ('date_commande', models.DateField()),
                ('date_livraison_prevue', models.DateField()),
                ('date_livraison_reelle', models.DateField(blank=True, null=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=14)),
                ('statut_appro', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'approvisionnement',
                'verbose_name_plural': 'approvisionnements',
            },
        ),
        migrations.CreateModel(
            name='Subir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approvisionnement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='approvisionnement.approvisionnement')),
            ],
            options={
                'verbose_name': 'association subir',
                'verbose_name_plural': 'associations subir',
                'db_table': 'subir',
            },
        ),
    ]
