# Generated by Django 6.0.6 on 2026-07-14 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activites', '0002_remove_activite_cout'),
        ('approvisionnement', '0002_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subir',
            name='uniq_subir_projet_appro',
        ),
        migrations.AddField(
            model_name='subir',
            name='activite',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='activites.activite'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='subir',
            constraint=models.UniqueConstraint(fields=('activite', 'approvisionnement'), name='uniq_subir_activite_appro'),
        ),
        migrations.RemoveField(
            model_name='subir',
            name='projet',
        ),
    ]
