# Generated by Django 6.0.6 on 2026-07-01 11:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Impliquer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'association impliquer',
                'verbose_name_plural': 'associations impliquer',
                'db_table': 'impliquer',
            },
        ),
        migrations.CreateModel(
            name='Particier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'association particier',
                'verbose_name_plural': 'associations particier',
                'db_table': 'particier',
            },
        ),
        migrations.CreateModel(
            name='PartiePrenante',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('nom_entite', models.CharField(max_length=255)),
                ('role', models.CharField(blank=True, max_length=100)),
                ('attentes', models.TextField(blank=True)),
                ('exigences', models.TextField(blank=True)),
                ('pouvoir', models.CharField(blank=True, max_length=50)),
                ('interet', models.CharField(blank=True, max_length=50)),
                ('strategie_engagement', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'partie prenante',
                'verbose_name_plural': 'parties prenantes',
            },
        ),
    ]
