# Generated by Django 6.0.6 on 2026-07-01 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activites', '0001_initial'),
        ('parties_prenantes', '0001_initial'),
        ('projets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='impliquer',
            name='projet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projets.projet'),
        ),
        migrations.AddField(
            model_name='particier',
            name='activite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activites.activite'),
        ),
        migrations.AddField(
            model_name='partieprenante',
            name='activites',
            field=models.ManyToManyField(blank=True, related_name='parties_prenantes', through='parties_prenantes.Particier', to='activites.activite'),
        ),
        migrations.AddField(
            model_name='particier',
            name='partie_prenante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parties_prenantes.partieprenante'),
        ),
        migrations.AddField(
            model_name='impliquer',
            name='partie_prenante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parties_prenantes.partieprenante'),
        ),
        migrations.AddConstraint(
            model_name='particier',
            constraint=models.UniqueConstraint(fields=('partie_prenante', 'activite'), name='uniq_particier_pp_activite'),
        ),
        migrations.AddConstraint(
            model_name='impliquer',
            constraint=models.UniqueConstraint(fields=('projet', 'partie_prenante'), name='uniq_impliquer_projet_pp'),
        ),
    ]
