# Generated by Django 6.0.6 on 2026-07-17 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties_prenantes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partieprenante',
            name='droits_acces',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='partieprenante',
            name='raci',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
