# Generated by Django 6.0.6 on 2026-07-28 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties_prenantes', '0003_partieprenante_droits_acces_partieprenante_raci'),
    ]

    operations = [
        migrations.AddField(
            model_name='partieprenante',
            name='signature_image',
            field=models.TextField(blank=True),
        ),
    ]
