# Generated by Django 6.0.6 on 2026-07-01 11:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wbs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Risque',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('description_risque', models.TextField()),
                ('probabilite', models.PositiveSmallIntegerField(help_text='Echelle a confirmer (ex: 1-5).')),
                ('impact', models.PositiveSmallIntegerField(help_text='Echelle a confirmer (ex: 1-5).')),
                ('score_risque', models.PositiveSmallIntegerField(help_text='Generalement probabilite x impact, a confirmer si calcule ou saisi.')),
                ('description_mitigation', models.TextField(blank=True)),
                ('responsable_mitigation', models.CharField(blank=True, max_length=255)),
                ('categorie_risque', models.CharField(max_length=50)),
                ('date_identification', models.DateField()),
                ('statut_risque', models.CharField(max_length=50)),
                ('wbs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risques', to='wbs.wbs')),
            ],
            options={
                'verbose_name': 'risque',
                'verbose_name_plural': 'risques',
            },
        ),
    ]
