# Generated by Django 6.0.6 on 2026-07-01 11:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('couts', '0001_initial'),
        ('wbs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('code_activite', models.CharField(max_length=50)),
                ('nom_activite', models.CharField(max_length=255)),
                ('description_activite', models.TextField(blank=True)),
                ('date_debut_prevue', models.DateField()),
                ('date_fin_prevue', models.DateField()),
                ('duree_estimee', models.PositiveIntegerField(help_text='Duree estimee, unite a confirmer (jours ?).')),
                ('progression', models.PositiveSmallIntegerField(default=0, help_text="Pourcentage d'avancement (0-100).")),
                ('statut_activite', models.CharField(max_length=50)),
                ('predecesseurs', models.TextField(blank=True, help_text='Codes des activites predecesseurs (a structurer plus tard).')),
                ('type_dependance', models.CharField(blank=True, max_length=50)),
                ('cout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activites', to='couts.cout')),
                ('wbs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activites', to='wbs.wbs')),
            ],
            options={
                'verbose_name': 'activite',
                'verbose_name_plural': 'activites',
            },
        ),
    ]
