# Generated by Django 6.0.6 on 2026-07-10 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activites', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activite',
            name='cout',
        ),
    ]
