# Generated by Django 6.0.6 on 2026-09-14 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activites', '0002_remove_activite_cout'),
    ]

    operations = [
        migrations.AddField(
            model_name='activite',
            name='activite_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sous_activites', to='activites.activite'),
        ),
    ]
