# Generated by Django 6.0.6 on 2026-09-17 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activites', '0003_activite_activite_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activite',
            options={'ordering': ['ordre', 'cree_le'], 'verbose_name': 'activite', 'verbose_name_plural': 'activites'},
        ),
        migrations.AddField(
            model_name='activite',
            name='ordre',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
