# Generated by Django 6.0.6 on 2026-07-01 11:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perimetre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('enonce_perimetre', models.TextField(blank=True)),
                ('criteres_acceptation', models.TextField(blank=True)),
                ('inclusions_perimetre', models.TextField(blank=True)),
                ('exclusions_perimetre', models.TextField(blank=True)),
                ('contraintes', models.TextField(blank=True)),
                ('hypotheses', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'perimetre',
                'verbose_name_plural': 'perimetres',
            },
        ),
    ]
