# Generated by Django 6.0.6 on 2026-07-01 11:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livrable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('nom_livrable', models.CharField(max_length=255)),
                ('description_livrable', models.TextField(blank=True)),
                ('type_livrable', models.CharField(max_length=50)),
                ('date_livraison_prevue', models.DateField()),
                ('date_livraison_reelle', models.DateField(blank=True, null=True)),
                ('statut_livrable', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'livrable',
                'verbose_name_plural': 'livrables',
            },
        ),
    ]
