# Generated by Django 6.0.6 on 2026-07-01 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('livrables', '0001_initial'),
        ('projets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livrable',
            name='projet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livrables', to='projets.projet'),
        ),
    ]
