# Generated by Django 6.0.6 on 2026-07-01 11:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('poste_budgetaire', models.CharField(max_length=255)),
                ('montant_estime', models.DecimalField(decimal_places=2, max_digits=14)),
                ('montant_reel', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('devise', models.CharField(max_length=3)),
                ('type_cout', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'cout',
                'verbose_name_plural': 'couts',
            },
        ),
    ]
