# Generated by Django 6.0.6 on 2026-07-01 11:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ressource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('nom_ressource', models.CharField(max_length=255)),
                ('role', models.CharField(blank=True, max_length=100)),
                ('type_ressource', models.CharField(max_length=50)),
                ('cout_unitaire', models.DecimalField(decimal_places=2, max_digits=14)),
                ('unite_mesure', models.CharField(max_length=50)),
                ('activite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ressources', to='activites.activite')),
            ],
            options={
                'verbose_name': 'ressource',
                'verbose_name_plural': 'ressources',
            },
        ),
    ]
