# Generated by Django 6.0.6 on 2026-09-15 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ressources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ressource',
            name='quantite',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=14),
        ),
    ]
