# Generated by Django 6.0.6 on 2026-07-01 11:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WBS',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('code_wbs', models.CharField(max_length=50)),
                ('nom_travail', models.CharField(max_length=255)),
                ('description_travail', models.TextField(blank=True)),
                ('niveau_hierarchie', models.PositiveSmallIntegerField(help_text="Niveau dans l'arborescence WBS (0 = racine).")),
                ('date_debut_prevue', models.DateField()),
                ('date_fin_prevue', models.DateField()),
                ('duree_estimee', models.PositiveIntegerField(help_text='Duree estimee, unite a confirmer (jours ?).')),
                ('wbs_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enfants', to='wbs.wbs')),
            ],
            options={
                'verbose_name': 'element WBS',
                'verbose_name_plural': 'elements WBS',
            },
        ),
    ]
