# Generated by Django 6.0.6 on 2026-07-10 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0001_initial'),
        ('wbs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wbs',
            name='projet',
            field=models.ForeignKey(default='00000000-0000-0000-0000-000000000000', on_delete=django.db.models.deletion.CASCADE, related_name='wbs_elements', to='projets.projet'),
            preserve_default=False,
        ),
    ]
