# Generated by Django 6.0.6 on 2026-09-17 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wbs', '0002_wbs_projet'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wbs',
            options={'ordering': ['ordre', 'cree_le'], 'verbose_name': 'element WBS', 'verbose_name_plural': 'elements WBS'},
        ),
        migrations.AddField(
            model_name='wbs',
            name='ordre',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
