# Generated by Django 6.0.6 on 2026-07-01 11:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Charte',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('nom_charte', models.CharField(max_length=255)),
                ('description_charte', models.TextField(blank=True)),
                ('probleme_opportunite', models.TextField(blank=True)),
                ('justification_projet', models.TextField(blank=True)),
                ('statut_charte', models.CharField(max_length=50)),
                ('date_approbation', models.DateField(blank=True, null=True)),
                ('commentaires_approbation', models.TextField(blank=True)),
                ('version_charte', models.CharField(max_length=20)),
                ('alignement_strategique', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'charte de projet',
                'verbose_name_plural': 'chartes de projet',
            },
        ),
    ]
