# Generated by Django 6.0.6 on 2026-07-17 22:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charte', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='charte',
            name='chef_projet',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='charte',
            name='localisation',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='charte',
            name='objectif_general',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='charte',
            name='objectifs_specifiques',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='charte',
            name='signataire_nom',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='charte',
            name='signataire_role',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='charte',
            name='signature_image',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='charte',
            name='sponsor_ouvrage',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='charte',
            name='type_projet',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='LigneBudgetairePrevisionnelle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('designation', models.CharField(max_length=255)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('quantite', models.DecimalField(decimal_places=2, default=1, max_digits=12)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('charte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_budgetaires', to='charte.charte')),
            ],
            options={
                'verbose_name': 'ligne budgetaire previsionnelle',
                'verbose_name_plural': 'lignes budgetaires previsionnelles',
                'ordering': ['ordre', 'cree_le'],
            },
        ),
    ]
