# Generated by Django 6.0.6 on 2026-07-23 11:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charte', '0002_charte_chef_projet_charte_localisation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LigneCalendrierPrevisionnel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('phase', models.CharField(max_length=255)),
                ('duree', models.CharField(blank=True, max_length=50)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('activites_cles', models.TextField(blank=True)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('charte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_calendrier', to='charte.charte')),
            ],
            options={
                'verbose_name': 'ligne calendrier previsionnel',
                'verbose_name_plural': 'lignes calendrier previsionnel',
                'ordering': ['ordre', 'cree_le'],
            },
        ),
    ]
