# Generated by Django 6.0.6 on 2026-09-14 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charte', '0003_lignecalendrierprevisionnel'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignebudgetaireprevisionnelle',
            name='unite',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
