# Generated by Django 6.0.6 on 2026-09-15 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charte', '0004_lignebudgetaireprevisionnelle_unite'),
    ]

    operations = [
        migrations.AddField(
            model_name='charte',
            name='duree_estimative',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
