# Generated by Django 6.0.6 on 2026-09-15 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charte', '0005_charte_duree_estimative'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignebudgetaireprevisionnelle',
            name='phase',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='lignebudgetaireprevisionnelle',
            name='tache_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sous_taches', to='charte.lignebudgetaireprevisionnelle'),
        ),
    ]
