# Generated by Django 6.0.6 on 2026-07-01 11:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('approvisionnement', '0001_initial'),
        ('charte', '0001_initial'),
        ('parties_prenantes', '0001_initial'),
        ('perimetre', '0001_initial'),
        ('wbs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('nom_projet', models.CharField(max_length=255)),
                ('code_projet', models.CharField(max_length=50, unique=True)),
                ('description_projet', models.TextField(blank=True)),
                ('date_creation', models.DateField()),
                ('date_debut_prevue', models.DateField()),
                ('date_fin_prevue', models.DateField()),
                ('statut_projet', models.CharField(max_length=50)),
                ('budget_total', models.DecimalField(decimal_places=2, max_digits=16)),
                ('approvisionnements', models.ManyToManyField(blank=True, related_name='projets', through='approvisionnement.Subir', to='approvisionnement.approvisionnement')),
                ('charte', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projet', to='charte.charte')),
                ('parties_prenantes', models.ManyToManyField(blank=True, related_name='projets', through='parties_prenantes.Impliquer', to='parties_prenantes.partieprenante')),
                ('perimetre', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projet', to='perimetre.perimetre')),
                ('projet_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sous_projets', to='projets.projet')),
                ('wbs_racine', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projet_racine', to='wbs.wbs')),
            ],
            options={
                'verbose_name': 'projet',
                'verbose_name_plural': 'projets',
            },
        ),
    ]
