# Generated by Django 6.0.6 on 2026-07-14 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projet',
            name='approvisionnements',
        ),
    ]
