# Generated by Django 6.0.6 on 2026-09-15 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0002_remove_projet_approvisionnements'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='ordre',
            field=models.IntegerField(default=0),
        ),
    ]
