# Generated by Django 6.0.6 on 2026-09-15 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0003_projet_ordre'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='taux_frais',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='projet',
            name='taux_majorations',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='projet',
            name='taux_marge_aleas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
